### ISSUE TITLE
[Friends/Followers] Integration of Friends Profiles List with Account Data

### ISSUE THREAD

**Issue by adiep2** [CMPUT301F21T05/TheGreatGitastrophe#46]
Story Points:

Description:
Friends List needs to be integrated into firebase.

AC:

A friends list needs to be stored on firebase along with the add/approve list.

**Comment by Ryden-Graham** [comment]
todo: - add two lists to accounts: a friends list and a pending list
- potentially add getters/setters to value copy these lists (unless we only use basic types)
